#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: spug
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spug-server
  namespace: spug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-spug-spug-server
  template:
    metadata:
      labels:
        app: deployment-spug-spug-server
    spec:
      volumes:
      - configMap:
          name: spug-conf
        name: spug-conf
      containers:
      - args:
        image: {{ .Values.global.docker_registry }}/{{ .Values.global.docker_namespace }}/spug_server_demo:{{ .Values.global.version }}
        imagePullPolicy: Always
        name: spug-server
        ports:
        - containerPort: 8000
          name: 8000tcp01
          protocol: TCP
        resources: {}
        securityContext:
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/spug/spug_api/spug.conf
          name: spug-conf
          subPath: spug.conf
        workingDir: /data/spug/spug_api
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-key
      restartPolicy: Always


