---

apiVersion: v1
kind: Service
metadata:
  name: spug-server
  namespace: spug
spec:
  ports:
  - name: 8000tcp00-spug
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30008
  selector:
    app: deployment-spug-spug-server
  sessionAffinity: None
  type: NodePort

