---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: spug
spec:
  ports:
  - name: mysqlport
    nodePort: 32004
    port: 3306
    protocol: TCP
    targetPort: dbport
  selector:
    app: mysql
  sessionAffinity: None
  type: NodePort