---

apiVersion: v1
kind: Service
metadata:
  name: spug-web
  namespace: spug
spec:
  ports:
  - name: 80tcp00-spug
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  selector:
    app: deployment-spug-spug-web
  sessionAffinity: None
  type: NodePort

