---
apiVersion: v1
kind: Namespace
metadata:
  name: spug
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spug-server
  namespace: spug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-spug-spug-server
  template:
    metadata:
      labels:
        app: deployment-spug-spug-server
    spec:
      volumes:
      - configMap:
          name: spug-conf
        name: spug-conff

      containers:
      - args:
        image: registry.cn-shenzhen.aliyuncs.com/guance-south/spug_server_demo:1.0
        imagePullPolicy: IfNotPresent
        name: spug-server
        ports:
        - containerPort: 8000
          name: 8000tcp01
          protocol: TCP
        resources: {}
        securityContext:
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/spug/spug_api/spug.conf
          name: spug-conf
          subPath: spug.conf
        workingDir: /data/spug/spug_api
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-key
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: spug-server
  namespace: spug
spec:
  ports:
  - name: 8000tcp00-spug
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30008
  selector:
    app: deployment-spug-spug-server
  sessionAffinity: None
  type: NodePort
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spug-conf
  namespace: spug
data:
  #### spug
  spug.conf: |
    [mysql]
    db_host=mysql.spug
    db_port=3306
    db_user=root
    db_password=admin@123456
    db_database=spug

    [ddtrace]
    dd_service=python-spug-demo
    dd_env=test
    dd_version=1.1
    dd_logs_injection=true
    dd_remote_configuration_enabled=true
    dd_agent_host=47.106.191.26
    dd_agent_port=9529

    [redis]
    redis_host=redis.spug
    redis_port=6379
    redis_password=viFRKZiZkoPmXnyF

    [rum]
    applicationId=spug_web
    datakitOrigin=http://47.106.191.26:9529
    env=dev
    version=1.0.0
    service=spug_web
    sessionSampleRate=100
    sessionReplaySampleRate=100
    trackInteractions=true
    traceType=ddtrace
    allowedTracingOrigins=[/.*/]
