---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: spug
spec:
  selector:
    app: redis
  type: NodePort
  ports:
    - name: redis-port
      protocol: TCP
      port: 6379
      targetPort: redis-port
