name: Deploy spug demo on kubernetes

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy to Kubernetes
        run: |
          echo "47.106.139.53 apiserver.cluster.local" | sudo tee -a /etc/hosts
          helm upgrade -i spug-server -f ./spug-helm/values.yaml --create-namespace --namespace spug spug-server ./spug-helm
